input-language C/C++
decl-version 2.0
var-comparability implicit


ppt ..fix_location():::ENTER


ppt ..fix_location():::EXIT
  ppt-type point
  variable *filename
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *stash->syms->name
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable *stash->syms->section
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable *unit->first_child_die_ptr
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_*stash->syms->name
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_*stash->syms->section
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->section_last
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->section_last->name
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->section_last->prev
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->section_last->symbol
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->section_last->symbol_ptr_ptr
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->sections
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->sections->name
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->sections->next
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->sections->symbol
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_abfd->sections->symbol_ptr_ptr
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_lh.standard_opcode_lengths
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->all_comp_units
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->last_comp_unit
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->sec
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->sec->name
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->sec->next
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->sec->prev
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->sec->symbol
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_stash->sec->symbol_ptr_ptr
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_table
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_table->files->name
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_unit
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_unit->abbrevs
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_unit->first_child_die_ptr
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GDiff_unit->stash
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GSize_abfd->filename
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GSize_filename
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable _GSize_unit->abbrevs
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable abfd->arch_info
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->build_id
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->filename
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->iovec
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->section_htab.newfunc
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->section_last
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->section_last->id
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable abfd->section_last->name
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->section_last->prev
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->section_last->symbol
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->section_last->symbol_ptr_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->section_last->used_by_bfd
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->sections
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->sections->id
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable abfd->sections->lma
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable abfd->sections->name
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->sections->next
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->sections->symbol
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->sections->symbol_ptr_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->sections->used_by_bfd
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable abfd->start_address
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable abfd->xvec
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable address
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable amt
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable exop_len
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable filename
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable i
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable lh.line_range
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable lh.opcode_base
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable lh.standard_opcode_lengths
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable line_end
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable line_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable low_pc
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable stash
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->adjusted_sections
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->all_comp_units
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->debug_sections
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->dwarf_line_buffer
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->info_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->info_ptr_end
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->info_ptr_memory
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->last_comp_unit
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec->id
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable stash->sec->name
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec->next
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec->prev
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec->symbol
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec->symbol_ptr_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec->used_by_bfd
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable stash->sec_info_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable table
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable table->comp_dir
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable table->dirs
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable table->files
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable table->files->dir
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable table->files->name
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable table->files->size
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable table->lcl_head
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable table->num_dirs
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable table->num_files
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable table->num_sequences
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable table->sequences
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->abbrevs
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->arange.high
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable unit->arange.low
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable unit->base_address
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable unit->comp_dir
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->end_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->first_child_die_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->info_ptr_unit
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->lang
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable unit->name
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->sec_info_ptr
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable unit->stash
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1