input-language C/C++
decl-version 2.0
var-comparability implicit


ppt ..fix_location():::ENTER


ppt ..fix_location():::EXIT
  ppt-type point
  variable *file->rede_files.last->ce_offset
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->ce_size
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->cl_offset
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->gid
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->mode
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->multi_extent
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->name.buffer_length
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->name.length
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->name_continues
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->nlinks
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->number
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->pz
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->pz_log2_bs
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->pz_uncompressed_size
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->rdev
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->re
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->re_descendant
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->rr_moved
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->rr_moved_has_re_only
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->size
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->symlink.buffer_length
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->symlink.length
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->symlink_continues
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->uid
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->rede_files.last->utf16be_bytes
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->symlink.s
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable *file->utf16be_name
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable a->client.dataset->data
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable a->filter->client_avail
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable a->filter->client_total
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable a->filter->data
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable a->passphrases.client_data
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable a->skip_file_ino
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable file->cl_offset
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->gid
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->mode
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->name.length
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->name.s
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable file->nlinks
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->number
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->rdev
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->rede_files.last
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable file->rr_moved
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->size
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->symlink.s
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable file->symlink_continues
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable file->utf16be_name
    var-kind variable
    rep-type hashcode
    dec-type ptr
    comparability 1
  variable iso9660->volume_block
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable iso9660->volume_size
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable skipsize
    var-kind variable
    rep-type int
    dec-type int
    comparability 1
  variable vd->location
    var-kind variable
    rep-type int
    dec-type int
    comparability 1


